#!/usr/bin/env bash
# Simulate a fresh user install from release archives.
#
# Usage: ./user-install-from-release.sh [slim|bundled]
#   Default: slim
#
# What it does:
#   1. Removes existing Mods/BOAM/ (clean install)
#   2. Removes generated icons from UserData/BOAM/icons/
#   3. Deploys the C# modpack via MCP (compile + install)
#   4. Extracts the engine archive into Mods/BOAM/
#   5. Verifies the install layout

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

VARIANT="${1:-slim}"
if [ "$VARIANT" != "slim" ] && [ "$VARIANT" != "bundled" ]; then
    echo "Usage: $0 [slim|bundled]"
    exit 1
fi

VERSION=$(jq -r '.version' modpack.json)
GAME_DIR="$HOME/.local/share/Steam/steamapps/common/Menace"
MOD_DIR="$GAME_DIR/Mods/BOAM"
ICONS_DIR="$GAME_DIR/UserData/BOAM/icons"
ARCHIVE="release/BOAM-tactical-engine-v${VERSION}-linux-x64-${VARIANT}.zip"

if [ ! -f "$ARCHIVE" ]; then
    echo "ERROR: Release archive not found: $ARCHIVE"
    echo "Run ./release.sh first."
    exit 1
fi

echo "==> Installing BOAM v${VERSION} from release (simulating fresh user install)"
echo ""

# Step 1: Clean existing mod
if [ -d "$MOD_DIR" ]; then
    echo "==> Removing existing Mods/BOAM/..."
    rm -rf "$MOD_DIR"
fi

# Step 2: Clean generated icons
if [ -d "$ICONS_DIR" ]; then
    echo "==> Removing existing icons..."
    rm -rf "$ICONS_DIR"
fi

# Step 3: Deploy C# modpack via deploy.sh (builds + compiles + installs DLL)
echo "==> Deploying C# modpack..."
./deploy.sh

# Step 4: Extract engine archive (overwrites engine binaries from deploy with release versions)
echo ""
echo "==> Extracting engine from $ARCHIVE..."
(cd "$GAME_DIR/Mods" && unzip -qo "$SCRIPT_DIR/$ARCHIVE")

# Step 5: Verify
echo ""
echo "==> Install layout:"
ls -la "$MOD_DIR/"
echo ""
echo "==> Configs:"
ls "$MOD_DIR/configs/"
echo ""

# Check icons
if [ -d "$ICONS_DIR" ]; then
    ICON_COUNT=$(find "$ICONS_DIR" -name "*.png" | wc -l)
    echo "==> Icons: $ICON_COUNT found"
else
    echo "==> Icons: none (will be auto-generated by tactical engine on first start)"
fi

echo ""
echo "==> Done. Launch the game via Steam to test."
echo "    Steam Launch Options: ~/.local/share/Steam/steamapps/common/Menace/Mods/BOAM/boam-launch.sh; WINEDLLOVERRIDES=\"version=n,b\" %command%"
